import { ParseRequest } from '../gen/messages_pb';
import { parseNTriples } from './parse_n_triples';
import { ctx } from './testkit';

// Independent oracle: canonical N-Triples grammar (absolute IRIs, one
// statement per line), hand-transcribed - not generated by this package.
const NTRIPLES_FIXTURE = `<http://example.org/alice> <http://xmlns.com/foaf/0.1/knows> <http://example.org/bob> .
<http://example.org/alice> <http://xmlns.com/foaf/0.1/name> "Alice"@en .
_:b0 <http://example.org/related> <http://example.org/alice> .
`;

describe('ParseNTriples', () => {
  it('parses the fixture into 3 quads with a DefaultGraph and no prefixes', async () => {
    const input = new ParseRequest();
    input.setText(NTRIPLES_FIXTURE);
    const result = await parseNTriples(ctx, input);

    expect(result.getError()).toBe('');
    const quads = result.getQuadsList();
    expect(quads).toHaveLength(3);
    expect(result.getPrefixesMap().getLength()).toBe(0); // N-Triples has no prefix syntax

    expect(quads[0].getSubject()!.getTermType()).toBe('NamedNode');
    expect(quads[0].getSubject()!.getValue()).toBe('http://example.org/alice');
    expect(quads[0].getGraph()!.getTermType()).toBe('DefaultGraph');

    expect(quads[1].getObject()!.getTermType()).toBe('Literal');
    expect(quads[1].getObject()!.getLanguage()).toBe('en');

    expect(quads[2].getSubject()!.getTermType()).toBe('BlankNode');
  });

  it('rejects a relative IRI even when base_iri is supplied (N-Triples requires absolute IRIs)', async () => {
    const input = new ParseRequest();
    input.setText('<#alice> <http://example.org/p> <http://example.org/o> .');
    input.setBaseIri('http://example.org/doc');
    const result = await parseNTriples(ctx, input);
    expect(result.getError()).not.toBe('');
    expect(result.getQuadsList()).toHaveLength(0);
  });

  it('returns a structured error on malformed N-Triples (missing terminating dot)', async () => {
    const input = new ParseRequest();
    input.setText('<http://example.org/a> <http://example.org/b> <http://example.org/c>\n');
    const result = await parseNTriples(ctx, input);
    expect(result.getError()).not.toBe('');
  });
});
