// Shared test context and fixture builders for rdf-tools node unit tests.
// Not a node and not a test file (no describe/it), so it is neither
// registered as a node nor collected by jest.
import {
  AxiomContext,
  AxiomLogger,
  AxiomSecrets,
  AxiomReflection,
  AxiomMutation,
} from '../gen/axiomContext';
import { Term, Quad } from '../gen/messages_pb';

const reflection: AxiomReflection = {
  flow: {
    nodes: [],
    edges: [],
    loopEdges: [],
    position: { currentInstance: 0, depth: 0, loopIterations: {}, subflowStackGraphIds: [] },
    graphId: '',
  },
};

const mutation: AxiomMutation = {
  flow: {
    addNode: (_p: string, _v: string) => 0,
    addEdge: (_s: number, _d: number) => {},
  },
};

export const ctx: AxiomContext = {
  log: { debug: () => {}, info: () => {}, warn: () => {}, error: () => {} } satisfies AxiomLogger,
  secrets: { get: (_n: string): [string, boolean] => ['', false] } satisfies AxiomSecrets,
  executionId: 'test-execution-id',
  flowId: 'test-flow-id',
  tenantId: 'test-tenant-id',
  reflection,
  mutation,
};

/** Builds a proto Term directly (bypassing any parser), for tests that
 * need a hand-constructed fixture independent of this package's own
 * Parse* nodes. */
export function iri(value: string): Term {
  const t = new Term();
  t.setTermType('NamedNode');
  t.setValue(value);
  return t;
}

export function blank(label: string): Term {
  const t = new Term();
  t.setTermType('BlankNode');
  t.setValue(label);
  return t;
}

export function lit(value: string, datatypeOrLang?: { datatype?: string; language?: string }): Term {
  const t = new Term();
  t.setTermType('Literal');
  t.setValue(value);
  if (datatypeOrLang?.language) {
    t.setLanguage(datatypeOrLang.language);
  } else {
    t.setDatatype(datatypeOrLang?.datatype ?? 'http://www.w3.org/2001/XMLSchema#string');
  }
  return t;
}

export const DEFAULT_GRAPH: Term = (() => {
  const t = new Term();
  t.setTermType('DefaultGraph');
  return t;
})();

export function mkQuad(subject: Term, predicate: Term, object: Term, graph: Term = DEFAULT_GRAPH): Quad {
  const q = new Quad();
  q.setSubject(subject);
  q.setPredicate(predicate);
  q.setObject(object);
  q.setGraph(graph);
  return q;
}

/**
 * INDEPENDENT ORACLE — a fixture RDF graph about three people, hand-
 * transcribed (not generated by calling this package). Reused across the
 * Parse, Count, Filter, GetSubjects, GetPredicates, GetObjects, and
 * GetPrefixes tests so the "known correct" quad set is defined exactly
 * once.
 *
 * Turtle source:
 *   @prefix ex: <http://example.org/> .
 *   @prefix foaf: <http://xmlns.com/foaf/0.1/> .
 *   ex:alice foaf:knows ex:bob, ex:carol .
 *   ex:alice foaf:name "Alice"@en .
 *   ex:alice foaf:age "30"^^<http://www.w3.org/2001/XMLSchema#integer> .
 *
 * Hand-counted facts about this document:
 *   - 4 triples total (2 from the comma-list "ex:bob, ex:carol").
 *   - distinct subjects: 1 (ex:alice).
 *   - distinct predicates: 3 (foaf:knows, foaf:name, foaf:age).
 *   - distinct objects: 4 (ex:bob, ex:carol, "Alice"@en, "30"^^xsd:integer).
 *   - 2 prefixes declared: ex, foaf.
 */
export const FIXTURE_TURTLE = `@prefix ex: <http://example.org/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
ex:alice foaf:knows ex:bob, ex:carol .
ex:alice foaf:name "Alice"@en .
ex:alice foaf:age "30"^^<http://www.w3.org/2001/XMLSchema#integer> .
`;

export const FIXTURE_PREFIXES: Record<string, string> = {
  ex: 'http://example.org/',
  foaf: 'http://xmlns.com/foaf/0.1/',
};

export const FIXTURE_QUADS: Quad[] = [
  mkQuad(iri('http://example.org/alice'), iri('http://xmlns.com/foaf/0.1/knows'), iri('http://example.org/bob')),
  mkQuad(iri('http://example.org/alice'), iri('http://xmlns.com/foaf/0.1/knows'), iri('http://example.org/carol')),
  mkQuad(
    iri('http://example.org/alice'),
    iri('http://xmlns.com/foaf/0.1/name'),
    lit('Alice', { language: 'en' })
  ),
  mkQuad(
    iri('http://example.org/alice'),
    iri('http://xmlns.com/foaf/0.1/age'),
    lit('30', { datatype: 'http://www.w3.org/2001/XMLSchema#integer' })
  ),
];

/**
 * INDEPENDENT ORACLE — the JSON-LD 1.1 spec's own primer-style example
 * (a person with a name and homepage, https://www.w3.org/TR/json-ld11/
 * section 2 "A Simple Example"), hand-transcribed with its own
 * hand-computed expanded form (schema.org IRIs resolved), not generated
 * by calling this package's own JsonLdExpand.
 */
export const JSONLD_FIXTURE_DOC = {
  '@context': {
    name: 'http://schema.org/name',
    homepage: { '@id': 'http://schema.org/url', '@type': '@id' },
  },
  '@id': 'http://example.org/people/alice',
  name: 'Alice',
  homepage: 'http://alice.example.org/',
};

// Hand-computed per the JSON-LD 1.1 Expansion algorithm: "name" -> full IRI
// key with a plain @value array; "homepage" -> full IRI key with an @id
// (since its context entry declares @type: "@id").
export const JSONLD_FIXTURE_EXPANDED = [
  {
    '@id': 'http://example.org/people/alice',
    'http://schema.org/name': [{ '@value': 'Alice' }],
    'http://schema.org/url': [{ '@id': 'http://alice.example.org/' }],
  },
];
